/*
 * TIM1_CFG.h
 *
 * Created: 9/19/2026 4:01:32 PM
 *  Author: Eltawel
 */ 


#ifndef TIM1_CFG_H_
#define TIM1_CFG_H_

typedef enum
{
	TIM1_NORMAL = 0,
	TIM1_PWM_PHASECORRECT_8_BIT,
	TIM1_PWM_PHASECORRECT_9_BIT,
	TIM1_PWM_PHASECORRECT_10_BIT,
	TIM1_CTC_OCR1A,
	TIM1_FASTPWM_8_BIT,
	TIM1_FASTPWM_9_BIT,
	TIM1_FASTPWM_10_BIT,
	TIM1_PWM_PHASE_FREQUENCY_CORRECT_ICR1,
	TIM1_PWM_PHASE_FREQUENCY_CORRECT_OCR1A,
	TIM1_PWM_PHASECORRECT_ICR1,
	TIM1_PWM_PHASECORRECT_OCR1A,
	TIM1_CTC_ICR1,
	TIM1_RESERVED,
	TIM1_FASTPWM_ICR1,
	TIM1_FASTPWM_OCR1A
}TIM1_WGM_t;

typedef enum
{
	TIM1_NO_CLK = 0,
	TIM1_NO_PRESCALING,
	TIM1_8_CLK,
	TIM1_64_CLK,
	TIM1_256_CLK,
	TIM1_1024_CLK
}TIM1_PRESCALER_t;


typedef enum
{
	TIM1_FALLING_EDGE = 0,
	TIM1_RISING_EDGE
}TIM1_EDGE_t;


#endif /* TIM1_CFG_H_ */